language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo build --verbose --features="hashmap_default_hasher";
      cargo test --verbose --features="hashmap_default_hasher";
      cargo bench --verbose --features="hashmap_default_hasher";
    else
      cargo build --verbose;
      cargo test --verbose;
    fi
notifications:
  email: false
